# SPDX-FileCopyrightText: 2023 Stoney Jackson <dr.stoney@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
image: gitpod/workspace-full:latest
tasks:
  - name: Install PLCC, Neovim, and setup dotfiles
    command: |
        # To pin to a specific version of PLCC,
        # in the next line, change main to something like v8.0.1
        PLCC_GIT_BRANCH=v8.0.1 \
          /bin/bash -c \
          "$(\curl -fsSL https://github.com/ourPLCC/plcc/raw/main/installers/plcc/install.bash)" \
          >> ~/.bashrc
        
        # Install Neovim
        sudo apt-get update
        sudo apt install neovim -y

        # Install GNU Stow
        sudo apt install stow -y

        # Clone dotfiles repository (replace with your actual repository URL)
        git clone https://github.com/yourusername/dotfiles.git ~/dotfiles

        # Navigate to dotfiles directory and stow nvim folder
        cd ~/dotfiles && stow nvim

        exec bash
vscode:
    extensions:
        - jebbs.plantuml
